
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jul 18 21:15:57 BOT 2016
//----------------------------------------------------

package ejemplocup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOR = 9;
  public static final int PUNTO = 6;
  public static final int INT = 17;
  public static final int IGUAL = 13;
  public static final int SEMI = 2;
  public static final int SUMA = 18;
  public static final int PALABRA = 28;
  public static final int BRKT_LFT = 23;
  public static final int IMPRIMIR = 26;
  public static final int PRT_LFT = 15;
  public static final int IGL_MAYOR = 10;
  public static final int IF = 14;
  public static final int CLASE = 25;
  public static final int OP_SUMA = 3;
  public static final int DIVIS = 21;
  public static final int COMMA = 22;
  public static final int MAYOR = 8;
  public static final int EOF = 0;
  public static final int MULTIP = 20;
  public static final int OP_DIV = 7;
  public static final int error = 1;
  public static final int OP_MULT = 5;
  public static final int ENTERO = 27;
  public static final int DIFF = 12;
  public static final int IGL_MENOR = 11;
  public static final int OP_RESTA = 4;
  public static final int BRKT_RGT = 24;
  public static final int PRT_RGT = 16;
  public static final int RESTA = 19;
}

