
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jul 19 20:59:26 BOT 2016
//----------------------------------------------------

package ejemplocup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOR = 4;
  public static final int IGUAL = 8;
  public static final int INT = 12;
  public static final int SEMI = 2;
  public static final int SUMA = 13;
  public static final int PALABRA = 24;
  public static final int BRKT_LFT = 19;
  public static final int POTENCIA = 17;
  public static final int IMPRIMIR = 22;
  public static final int PRT_LFT = 10;
  public static final int IGL_MAYOR = 5;
  public static final int IF = 9;
  public static final int CLASE = 21;
  public static final int DIVIS = 16;
  public static final int COMMA = 18;
  public static final int MAYOR = 3;
  public static final int EOF = 0;
  public static final int MULTIP = 15;
  public static final int error = 1;
  public static final int ENTERO = 23;
  public static final int DIFF = 7;
  public static final int IGL_MENOR = 6;
  public static final int BRKT_RGT = 20;
  public static final int PRT_RGT = 11;
  public static final int RESTA = 14;
}

